"""Added age column to User model

Revision ID: 462e5597c759
Revises: 
Create Date: 2024-07-29 00:21:31.379714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '462e5597c759'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admissionforms', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('photograph', schema=None) as batch_op:
        batch_op.alter_column('image_data',
               existing_type=mysql.LONGBLOB(),
               type_=sa.String(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photograph', schema=None) as batch_op:
        batch_op.alter_column('image_data',
               existing_type=sa.String(length=255),
               type_=mysql.LONGBLOB(),
               nullable=True)

    with op.batch_alter_table('admissionforms', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
